# Generated by Django 5.2.10 on 2026-05-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('agency', 'Agency')], default='student', max_length=20),
        ),
    ]
