# Generated by Django 5.2.14 on 2026-05-07 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0004_alter_opportunity_options_alter_opportunity_capacity_and_more'),
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Issued at'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities.opportunity', verbose_name='Opportunity'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='interests',
            field=models.CharField(blank=True, help_text='Write interests separated by commas, e.g. teaching, environment, community', max_length=255, null=True, verbose_name='Interests'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='major',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Major'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('agency', 'Agency'), ('admin', 'Admin')], default='student', max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='university_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='University ID'),
        ),
    ]
