# Generated by Django 5.2.10 on 2026-05-08 16:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0004_alter_opportunity_options_alter_opportunity_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='application_deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Application deadline'),
        ),
    ]
