# Generated by Django 5.2.10 on 2026-05-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
